version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-quotar
    hostname: db
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: senha12345
      MYSQL_ROOT_PASSWORD: senharoot123
      MYSQL_DATABASE: quotar-db
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - REDE1
  
  phpmyadmin:
    image: phpmyadmin:5.1
    container_name: phpmyadmin-quotar
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
    networks:
      - REDE1

volumes:
  mariadb_data:
    name: VOL1

networks:
  REDE1:
    external: true